### ISSUE TITLE
[FR] Use multiple User for Hub reports in a report config without loop

### ISSUE THREAD

**Issue by mossbeard** [senseexcel/ser-distribute-nuget#73]
![image](https://user-images.githubusercontent.com/26477924/50153557-11175500-02c7-11e9-8595-39c73e54db6f.png)

**Comment by AlexanderGoerlich** [comment]
we have to discuss that

**Comment by mossbeard** [comment]
Wir mit Issue #86 gelöst

**Comment by mossbeard** [comment]
same senseexcel/senseexcel-reporting#44
